package com.questionerx5.voistella;

public class StatMod{
    private ModType type;
    public ModType type(){
        return type;
    }
    private double amount;
    public double amount(){
        return amount;
    }
    public StatMod(ModType type, double amount){
        this.type = type;
        this.amount = amount;
    }

    static enum ModType{
        FLAT_INCREASE, MULT_INCREASE, MULT
    }

    // autogenerated
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((type == null) ? 0 : type.hashCode());
        long temp;
        temp = Double.doubleToLongBits(amount);
        result = prime * result + (int) (temp ^ (temp >>> 32));
        return result;
    }
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        StatMod other = (StatMod) obj;
        if (type != other.type)
            return false;
        if (Double.doubleToLongBits(amount) != Double.doubleToLongBits(other.amount))
            return false;
        return true;
    }
}
